services:
  tempvoice:
    image: ghcr.io/drahonn/tempvoice:latest
    container_name: tempvoice-bot
    restart: unless-stopped
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      GUILD_ID: ${GUILD_ID}
      CATEGORY_CHANNEL_ID: ${CATEGORY_CHANNEL_ID}
      EMBED_CHANNEL_ID: ${EMBED_CHANNEL_ID}
      VOICE_CHANNEL_ID: ${VOICE_CHANNEL_ID}
      LOG_CHANNEL_ID: ${LOG_CHANNEL_ID}
      BANNER_URL: ${BANNER_URL}
      USE_UNICODE_EMOJI: ${USE_UNICODE_EMOJI}
    volumes:
      - type: bind
        source: /opt/tempvoice/data/constants.js
        target: /usr/src/app/src/constants.js
      - type: bind
        source: /opt/tempvoice/data/config.js
        target: /usr/src/app/config/config.js
        bind:
          create_host_path: true
    healthcheck:
      test: ["CMD", "node", "--eval", "process.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    security_opt:
      - no-new-privileges:true
